spring:
  application:
    name: workflow-service
  config:
    import: "classpath:/common-application.yml"
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${flowforge.datasource.host}/${flowforge.datasource.db-name}?${flowforge.datasource.params}}
    username: ${flowforge.datasource.username}
    password: ${flowforge.datasource.password}
    driver-class-name: ${flowforge.datasource.driver-class-name}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: workflow
        hbm2ddl:
          create_namespaces: true

server:
  port: 8082
