server:
  port: 8081

spring:
  application:
    name: auth-service
  config:
    import: "classpath:/common-application.yml"
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${flowforge.datasource.host}/${flowforge.datasource.db-name}?${flowforge.datasource.params}}
    username: ${flowforge.datasource.username}
    password: ${flowforge.datasource.password}
    driver-class-name: ${flowforge.datasource.driver-class-name}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: auth
        hbm2ddl:
          create_namespaces: true

application:
  security:
    jwt:
      secret-key: ${APPLICATION_SECURITY_JWT_SECRET_KEY:dev-secret-key-please-change-dev-secret-key-please-change}
      expiration: ${APPLICATION_SECURITY_JWT_EXPIRATION:86400000}
      refresh-token:
        expiration: ${APPLICATION_SECURITY_JWT_REFRESH_TOKEN_EXPIRATION:604800000}
